jobs:
  stable:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y redis-server
      - restore_cache:
          key: project-cache
      - run: cargo build
      - run: cargo test -- --test-threads=1
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"

  nightly:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y redis-server
      - restore_cache:
          key: project-cache-nightly
      - run: rustup install nightly
      - run: cargo install grcov
      - run:
          name: Build and Test
          command: |
            cargo +nightly build
            cargo +nightly test -- --test-threads=1
          environment:
            CARGO_INCREMENTAL: 0
            RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort"
            RUSTDOCFLAGS: "-Cpanic=abort"
      - run:
          name: Upload Coverage Report
          command: |
            zip -0 ccov.zip `find . \( -name "copy_redis*.gc*" \) -print`;
            grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore "/*" -o lcov.info;
            bash <(curl -s https://codecov.io/bash) -f lcov.info
      - save_cache:
          key: project-cache-nightly
          paths:
            - "~/.cargo"
            - "./target"

workflows:
  version: 2
  stable_and_nightly:
    jobs:
      - stable
      - nightly