version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y redis-server
      - restore_cache:
          key: project-cache
      - run: cargo build
      - run: cargo test -- --nocapture
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"